[versions]
androidGradlePlugin = "8.9.1"
kotlin = "2.0.20"
googleServices = "4.4.2"
androidxCore = "1.13.1"
androidxAppcompat = "1.7.0"
material = "1.12.0"
androidxActivity = "1.9.3"
androidxConstraintlayout = "2.1.4"
androidxNavigation = "2.8.3"
firebaseBom = "33.5.1"
androidxCredentials = "1.3.0"
googleId = "1.1.1"
googlePlayServicesAuth = "21.2.0"
kotlinxCoroutines = "1.8.1"
androidxLifecycle = "2.8.6"
ccp = "2.7.3"
animatedbottombar = "1.1.0"  # Changed to stable release
amadeusJava = "9.0.0"
gson = "2.11.0"
junit = "4.13.2"
androidxJunit = "1.2.1"
espressoCore = "3.6.1"
androidxRecyclerview = "1.3.2"
<<<<<<< HEAD
firebaseDatabaseKtx = "21.0.0"
=======
>>>>>>> upstream/main

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
<<<<<<< HEAD
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
=======
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
>>>>>>> upstream/main
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidxNavigation" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "androidxCredentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "androidxCredentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleId" }
google-play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "googlePlayServicesAuth" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
ccp = { module = "com.hbb20:ccp", version.ref = "ccp" }
animatedbottombar = { module = "nl.joery.animatedbottombar:library", version.ref = "animatedbottombar" }  # Corrected group ID
amadeus-java = { module = "com.amadeus:amadeus-java", version.ref = "amadeusJava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidxRecyclerview" }
<<<<<<< HEAD
firebase-database-ktx = { group = "com.google.firebase", name = "firebase-database-ktx", version.ref = "firebaseDatabaseKtx" }
=======
>>>>>>> upstream/main

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }